version: '3'

services:
  db:
    image: 'postgres:13.1-alpine'
    environment:
      POSTGRESS_PASSWORD: postgres 
      POSTGRES_USER: postgres
      POSTGRES_DB: filefire
    
    volumes:
      - ./pgdata:/var/lib/postgressql/data

    ports:
        - '5432:5432'

  backend:
        build:
            context: './'
            target: 'development'
        volumes:
            - './:/usr/src/app'
        ports:
            - '8082:8082'
        depends_on:
            - db