version: '3'

services:
  db:
    image: 'postgres:13.1-alpine'
    environment:
      POSTGRESS_PASSWORD: postgres 
      POSTGRES_USER: postgres
      POSTGRES_DB: filefire
    
    volumes:
      - ./pgdata:/var/lib/postgressql/data

    ports:
        - '5432:5432'
   

  backend:
        build:
            context: './dev.Dockerfile'
        ports:
            - '8082:8082'
        volumes:
            - './:/usr/src/app'
        depends_on:
            - db
        deploy: 
            replicas: 6
        