name: Build

on:
  push:
    branches:
      - main

  pull_request:

env:
  IMAGE_NAME: filefire-backend

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose..yml ]; then
            docker-compose --file docker-compose.yml build
            docker-compose --file docker-compose.yml run sut
          else
            docker build . --file docker/dev.Dockerfile
          fi

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
